### ISSUE TITLE
[Question] How add command in Menu Bar?

### ISSUE THREAD

**Issue by Kristinita** [nsubiron/SublimeSuricate#4]
### Briefly

I want to add my command in menu bar, but not only in `Preferences` → `Package Settings` → `Suricate` item.

### Detail

Part of my `Default.suricate-profile` file:

```json
"git-bash": {
    "caption": "Bash",
    "group": "main.tools",
    "keys": ["<c>+super+keypad3"],
    "args.windows": {
        "cmd": ["C:\\Program Files\\Git\\git-bash.exe"],
        "working_dir": "${file_path}"
    },
    "call": "Suricate.lib.process.spawn",
    "context_menu": true
},
```

I want item `Bash` in `Tools` of Menu Bar. But I don't know, how I can make it.

### Did not help

I try `"group": "tools"`, `"group": "main.*"` and so on, but its no working for me. Only `"group": "main.preferences"` works for me:

![main.preferences](http://i.imgur.com/h8BH5mg.png)

Thanks.

**Comment by nsubiron** [comment]
Sorry, currently you can only add commands to the menu bar in 2 places
- `main.preferences`: adds to "Preferences → Package Settings → Suricate"
- `main.*`: adds to the "Suricate" menu, which only shows when the "dev mode" is on. They are grouped and sorted based on whatever you put on the `*`

The reason I put only those two is because I couldn't find a way to nicely sort the commands in other menus.

**Comment by Kristinita** [comment]
@nsubiron , do you plain to make a feature — add commands into other items of Menu bar?

Thanks.
